name: direction_button
description: "Button which expands and shows direction on hover"
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_inset_shadow: 2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 10.0.0

flutter:
  uses-material-design: false

  fonts:
    - family: Inter
      fonts:
        - asset: assets/Inter-Medium.ttf
          weight: 500
